### ISSUE TITLE
linux support?

### ISSUE THREAD

**Issue by darkst0rm223** [ebolite/suburb#1]
python cant find assets
![image](https://github.com/ebolite/suburb/assets/107277121/309386cd-3943-48a6-8257-c935bc7ac154)

**Comment by ebolite** [comment]
I just committed a change that should fix this particular error, but let me know. You might have some trouble running the game unless you can run the server yourself, as it's not up 24/7. If you want, you can join the [Discord server](https://discord.gg/k2uuDc9fvF) to stay updated on when playtest sessions are happening, and to troubleshoot the app on linux with me.
